# تعریف منطقه حافظه برای محدودسازی نرخ درخواست
limit_req_zone $binary_remote_addr zone=login_limit:10m rate=1r/s;

server {
    # nginx listens to this port
    listen 80;

    # the orginal path
    location / {

        # go to this route
        root /usr/share/nginx/html;

        # and show this file
        index index.html;
    }

    # Route trafic for authentication directly to the c# microservice
    location /api/auth/ {
        # اعمال سپر دفاعی و محدودیت روی مسیر احراز هویت
        limit_req zone=login_limit burst=3 nodelay;

        proxy_pass http://auth-service:8080;

        #standard code for saving information of sender
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # if route start with this /api/
    location /api/ {
        # pass the trafic to this addres
        proxy_pass http://user-service:5000;
        
        #standard code for saving information of sender
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}